## 1. Load Resume Dataset

In [1]:
import pandas as pd

df = pd.read_csv("../data/resumes/Resume.csv")

In [2]:
df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [3]:
df.columns

Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='str')

In [4]:
df.shape

(2484, 4)

## 2. Explore Resume Dataset

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           2484 non-null   int64
 1   Resume_str   2484 non-null   str
 2   Resume_html  2484 non-null   str
 3   Category     2484 non-null   str
dtypes: int64(1), str(3)
memory usage: 52.3 MB

In [6]:
df.isnull().sum()

ID             0
Resume_str     0
Resume_html    0
Category       0
dtype: int64

In [7]:
df["Category"].value_counts()

Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      120
ADVOCATE                  118
CHEF                      118
FINANCE                   118
ENGINEERING               118
ACCOUNTANT                118
FITNESS                   117
AVIATION                  117
SALES                     116
HEALTHCARE                115
CONSULTANT                115
BANKING                   115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [8]:
print(df["Resume_str"].iloc[0][:2000])

         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        Experience      HR Administrator/Marketing Associate

HR Administrator     Dec 2013   to   Current      Company Name   －   City  ,   State     Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  Prepares employee separation notices and related documentation  Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  Advises management in appropriate resolution of employee relations issues.  Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     Marketing Associate     Designed and created marketing collateral for sales meetings, trade sh

## 3. Prepare Resume Text

In [9]:
rag_df = df[["ID", "Resume_str", "Category"]].copy()

In [10]:
rag_df = rag_df.rename(columns={
    "Resume_str": "resume_text"
})

In [11]:
rag_df.head()

         ID                                        resume_text Category
0  16852973           HR ADMINISTRATOR/MARKETING ASSOCIATE\...       HR
1  22323967           HR SPECIALIST, US HR OPERATIONS      ...       HR
2  33176873           HR DIRECTOR       Summary      Over 2...       HR
3  27018550           HR SPECIALIST       Summary    Dedica...       HR
4  17812897           HR MANAGER         Skill Highlights  ...       HR

In [12]:
rag_df = rag_df.dropna(subset=["resume_text"])

rag_df = rag_df[
    rag_df["resume_text"].str.strip() != ""
].reset_index(drop=True)

In [13]:
print("Prepared resumes:", rag_df.shape)

Prepared resumes: (2483, 3)

In [14]:
import re

def clean_resume_text(text):
    text = str(text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

In [15]:
rag_df["clean_resume"] = rag_df["resume_text"].apply(clean_resume_text)

In [16]:
print(rag_df["clean_resume"].iloc[0][:2000])

HR ADMINISTRATOR/MARKETING ASSOCIATE HR ADMINISTRATOR Summary Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management. Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service. Highlights Focused on customer satisfaction Team management Marketing savvy Conflict resolution techniques Training and development Skilled multi-tasker Client relations specialist Accomplishments Missouri DOT Supervisor Training Certification Certified by IHG in Customer Loyalty and Marketing by Segment Hilton Worldwide General Manager Training Certification Accomplished Trainer for cross server hospitality systems such as Hilton OnQ , Micros Opera PMS , Fidelio OPERA Reservation System (ORS) , Holidex Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment. Experience HR Administrator/Marketing Associate HR Administrator Dec 2013 to Current Company Name － City , State Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services. Prepares employee separation notices and related documentation Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting. Advises management in appropriate resolution of employee relations issues. Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance. Marketing Associate Designed and created marketing collateral for sales meetings, trade shows and company executives. Managed the in-house advertising program consisting of print and media collateral pieces. Assisted in the com

In [17]:
rag_df[["ID", "Category", "clean_resume"]].head()

         ID Category                                       clean_resume
0  16852973       HR  HR ADMINISTRATOR/MARKETING ASSOCIATE HR ADMINI...
1  22323967       HR  HR SPECIALIST, US HR OPERATIONS Summary Versat...
2  33176873       HR  HR DIRECTOR Summary Over 20 years experience i...
3  27018550       HR  HR SPECIALIST Summary Dedicated, Driven, and D...
4  17812897       HR  HR MANAGER Skill Highlights HR SKILLS HR Depar...

## 4. Generate Resume Embeddings

In [18]:
from sentence_transformers import SentenceTransformer

e:\NLP\rag-talent-search-engine\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [19]:
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7478.03it/s]

In [20]:
resume_embeddings = embedding_model.encode(
    rag_df["clean_resume"].tolist(),
    show_progress_bar=True
)

Batches: 100%|██████████| 78/78 [01:10<00:00,  1.11it/s]

In [21]:
print(resume_embeddings.shape)

(2483, 384)

In [22]:
print(resume_embeddings[0][:10])

[-0.04447829  0.02122919  0.00516218  0.08680715 -0.01907622  0.00078137
  0.02372742 -0.04067285 -0.10769627 -0.04174348]

## 5. Build FAISS Vector Database

In [23]:
import faiss
import numpy as np

In [24]:
resume_embeddings = np.array(
    resume_embeddings,
    dtype="float32"
)

In [25]:
embedding_dimension = resume_embeddings.shape[1]

print("Embedding dimension:", embedding_dimension)

Embedding dimension: 384

In [26]:
index = faiss.IndexFlatL2(embedding_dimension)

In [27]:
index.add(resume_embeddings)

In [28]:
print("Vectors stored:", index.ntotal)

Vectors stored: 2483

In [29]:
faiss.write_index(
    index,
    "../vector_db/resume_index.faiss"
)

In [30]:
import os

print(
    os.path.exists(
        "../vector_db/resume_index.faiss"
    )
)

True

## 6. Semantic Resume Search

In [31]:
def search_resumes(query, top_k=5):
    query_embedding = embedding_model.encode([query])

    query_embedding = np.array(
        query_embedding,
        dtype="float32"
    )

    distances, indices = index.search(
        query_embedding,
        top_k
    )

    results = []

    for rank, resume_index in enumerate(indices[0]):
        candidate = rag_df.iloc[resume_index]

        results.append({
            "rank": rank + 1,
            "id": candidate["ID"],
            "category": candidate["Category"],
            "distance": distances[0][rank],
            "resume": candidate["clean_resume"]
        })

    return results

In [32]:
query = """
Find me a candidate with Python,
SQL, data analysis, and machine learning experience.
"""

results = search_resumes(query, top_k=5)

In [33]:
for result in results:
    print("=" * 80)
    print("Rank:", result["rank"])
    print("Candidate ID:", result["id"])
    print("Category:", result["category"])
    print("FAISS Distance:", result["distance"])
    print()
    print(result["resume"][:1000])
    print()

================================================================================
Rank: 1
Candidate ID: 62994611
Category: AGRICULTURE
FAISS Distance: 0.8822707

SOFTWARE DEVELOPER Professional Summary Enthusiastic computer engineer eager to contribute to team success through hard work, attention to detail and excellent organizational skills. Technical professional with complete understanding of entire software development life cycle. Respectful self-motivator gifted at finding reliable solutions for software issues. Experienced in c#, python, HTML, SQL, node.js/javascript and working knowledge of Restful API design & implementations. Fluent in English and Turkish and accustomed to working with cross-cultural, global teams. Skills C#, HTML, CSS, JavaScript, 5 years of experience SQL, 5 years of experience Python, MatLab, MongoDB, Tableau, Node JS Frameworks: .Net, Devexpress, TensorFlow, Keras, Scikit-learn, Pandas, NLTK. Search Engine Optimization Net API CSS Clients Database development Designing English HTML Image processing JavaScript Leadership Marketing MatLab C# Office Windows Project management Speaker Python Sales Search Engine Optimiz

================================================================================
Rank: 2
Candidate ID: 18448085
Category: AUTOMOBILE
FAISS Distance: 0.9249978

DATA ANALYST Professional Summary Industrial and Systems Engineering graduate, certified Base SAS Programmer and a Lean Six Sigma Green Belt with strong background in statistics, mathematics and logical problem solving looking for a dynamic opportunity in data driven fields of analytics and statistical modeling. Core Qualifications Data Science Tools: R, Base SAS, Python (Numpy, Pandas, Matplotlib, Scikit- learn), SPSS, Minitab, MATLAB, Apache Spark, SQL, MS Excel, MS Visio, Tableau MySQL, Oracle Database, Microsoft Access Key Competencies: Data Extraction, Data Wrangling, Data Analysis, Data Visualization, Regression Analysis (Linear, Logistic and Multinomial), Time Series Analysis, Association Rule Mining, Monte Carlo Simulation, Optimization, Random Forests Experience 07/2016 to Current Data Analyst Company Name － State 09/2015 to 05/2016 Student Manager Company Name － State Undertook a leadership and advisory role in training newcomers to hone their culinary and behavioral skills.

================================================================================
Rank: 3
Candidate ID: 30863060
Category: CONSULTANT
FAISS Distance: 0.97594476

CONSULTANT Summary College graduate with interest in insurance claims work. Proven record of success in all endeavors. Strong work ethic and focus on the details. Excited to begin career in investigative work. Searching for an entry level position as an insurance claims adjuster. Skills Unix, SQL Server 2005, SQL Server 2008, SQL Server 2008R2, VM-Ware, ODBC, SQL, PL/SQL, Access, MS Office Suite, MS Visio, Oracle 10g, Oracle 11g, SAP Business Objects BI Suite, PeopleSoft, ADP, and cView SAP Business Objects Suite, MS Reporting Suite, MicroStrategy, MS Office Suite, Tableau Industry Software: SQL Server Studio, EmpCenter, CQCS, DNA, DNA-sme, IMC, eSoms, and cView Web Design: Internet Explorer, Netscape Navigator, Chrome, Firefox, JAVA, ASP.NET, and HTML Operating Systems: MS Windows Professional/Enterprise/XP/7/8, NT, Novell NetWare Server Environments: SQL 2008, SQL 2008R2, SQL 2012, Oracle 11g, Oracle 11g2, and RPG Metadata, SAS, PeopleSoft, ADP, Ceridian Encore, SSRS, SSAS, SSIS, ETL

================================================================================
Rank: 4
Candidate ID: 12011623
Category: ENGINEERING
FAISS Distance: 0.9940244

ENGINEERING AND QUALITY TECHNICIAN Career Overview A highly experienced skilled graduate with Analytics degree with a very good experience in SAS, Web scraping, SQL, Predictive modelling and data visualization. Excellent ability in identifying data requirements for analysis, data cleaning, munging and model building; Ensures the organization uses it effectively to reach profit and growth objectives. Comfortable with data handling, modeling, and coding, and have an appreciation of what makes sense from a business standpoint. More than six years of experience working as a researcher, data analyst, and environmental science and Technology Instructor. Experience in SQL, data warehousing, maintaining, securing and stabilizing data layers and testing to identify data and product defects introduced in the system. Customer segmentation, product positioning and mapping and conjoint analysis Modelling: Design and implement statistical / predictive models and cutting edge algorithms utilizing div

================================================================================
Rank: 5
Candidate ID: 12144825
Category: AVIATION
FAISS Distance: 0.99472505

SOFTWARE ENGINEERING CO-OP Summary Highly skilled and Accomplished computer software specialist with more than 7+ years of technical experience in programming development across multiple platforms, software design, development and integration. Advanced knowledge of MySQL, CSS, C++ with expertise in all aspects of the software development life cycle, including requirements analysis, design, development and production support. Experienced Software Developer dedicated to constantly improving tools and infrastructure to maximize productivity, minimize system downtime and quickly respond to the changing needs of the business which does not exclude an intensive background in develop, testing, and debugging code, designing interfaces, and administrating systems and networks. Tenacious hard worker, self-directed and motivated, great leadership skills, able to work as a team, and adaptable to a quick changing technical environment. Highlights MySQL, PostgreSQL, SQLite, NoSQL, LevelDB Programmin

## 7. Display Retrieved Candidates

In [34]:
def display_results(results):
    for result in results:
        print("=" * 100)
        print(f"Rank: {result['rank']}")
        print(f"Candidate ID: {result['id']}")
        print(f"Category: {result['category']}")
        print(f"FAISS Distance: {result['distance']:.4f}")
        print("-" * 100)
        print(result["resume"][:1500])
        print()

In [35]:
display_results(results)

====================================================================================================
Rank: 1
Candidate ID: 62994611
Category: AGRICULTURE
FAISS Distance: 0.8823
----------------------------------------------------------------------------------------------------
SOFTWARE DEVELOPER Professional Summary Enthusiastic computer engineer eager to contribute to team success through hard work, attention to detail and excellent organizational skills. Technical professional with complete understanding of entire software development life cycle. Respectful self-motivator gifted at finding reliable solutions for software issues. Experienced in c#, python, HTML, SQL, node.js/javascript and working knowledge of Restful API design & implementations. Fluent in English and Turkish and accustomed to working with cross-cultural, global teams. Skills C#, HTML, CSS, JavaScript, 5 years of experience SQL, 5 years of experience Python, MatLab, MongoDB, Tableau, Node JS Frameworks: .Net, Devexpress, TensorFlow, Keras, Scikit-learn, Pandas, NLTK. Search Engine Optimization Net API CSS Clients Database development Designing English HTML Image processing JavaScript Leadership Marketing MatLab C# Office Windows Project management Speaker Python Sales Search Engine Optimization Spanish SQL System architecture Turkish User Interface Web site Written Work History Software Developer , 12/2015 to Current Company Name – City , State Project was tasked to design an Internal Marketing System using c#,SQL, HTML,.net, devexpress. Amazon,Walmart,eBay and Shopify. API's were integrated. The system records the end to end process. A scalable system architecture to support high-availability Internet site with various internal applicationswas key. My responsibilities were:. Int

====================================================================================================
Rank: 2
Candidate ID: 18448085
Category: AUTOMOBILE
FAISS Distance: 0.9250
----------------------------------------------------------------------------------------------------
DATA ANALYST Professional Summary Industrial and Systems Engineering graduate, certified Base SAS Programmer and a Lean Six Sigma Green Belt with strong background in statistics, mathematics and logical problem solving looking for a dynamic opportunity in data driven fields of analytics and statistical modeling. Core Qualifications Data Science Tools: R, Base SAS, Python (Numpy, Pandas, Matplotlib, Scikit- learn), SPSS, Minitab, MATLAB, Apache Spark, SQL, MS Excel, MS Visio, Tableau MySQL, Oracle Database, Microsoft Access Key Competencies: Data Extraction, Data Wrangling, Data Analysis, Data Visualization, Regression Analysis (Linear, Logistic and Multinomial), Time Series Analysis, Association Rule Mining, Monte Carlo Simulation, Optimization, Random Forests Experience 07/2016 to Current Data Analyst Company Name － State 09/2015 to 05/2016 Student Manager Company Name － State Undertook a leadership and advisory role in training newcomers to hone their culinary and behavioral skills. PROJECTS Classification of Customers for Credit Card Company Jan 2016 ­ May 2016 Performed a logistic regression on a credit card company dataset to classify clients as credible and non-credible. Extracted crucial factors to simplify the classification model using exploratory factor analysis. Developed and validated a model to classify the future customers and aid decision-making. Simulation Analysis of Adding a Second Parking Ticket Booth at a Mall Aug 2015 ­ Dec 2015 Assessed distribution and

====================================================================================================
Rank: 3
Candidate ID: 30863060
Category: CONSULTANT
FAISS Distance: 0.9759
----------------------------------------------------------------------------------------------------
CONSULTANT Summary College graduate with interest in insurance claims work. Proven record of success in all endeavors. Strong work ethic and focus on the details. Excited to begin career in investigative work. Searching for an entry level position as an insurance claims adjuster. Skills Unix, SQL Server 2005, SQL Server 2008, SQL Server 2008R2, VM-Ware, ODBC, SQL, PL/SQL, Access, MS Office Suite, MS Visio, Oracle 10g, Oracle 11g, SAP Business Objects BI Suite, PeopleSoft, ADP, and cView SAP Business Objects Suite, MS Reporting Suite, MicroStrategy, MS Office Suite, Tableau Industry Software: SQL Server Studio, EmpCenter, CQCS, DNA, DNA-sme, IMC, eSoms, and cView Web Design: Internet Explorer, Netscape Navigator, Chrome, Firefox, JAVA, ASP.NET, and HTML Operating Systems: MS Windows Professional/Enterprise/XP/7/8, NT, Novell NetWare Server Environments: SQL 2008, SQL 2008R2, SQL 2012, Oracle 11g, Oracle 11g2, and RPG Metadata, SAS, PeopleSoft, ADP, Ceridian Encore, SSRS, SSAS, SSIS, ETL, Access, Excel, Teradata, Crystal Reports, ServiceNow, SharePoint, and Cyberquery Experience Consultant 07/2016 to Current Company Name City , State Top 4 Financial Institution) Create SQL queries, stored procedures, and tables to extract data Analyze data to create executive team dashboards and daily visualizations Utilize Excel pivot tables to monitor observations within the Core Finance metadata template Analyze Core Finance and GBAM Americas feeds for manual spreadsheet remediation Support

====================================================================================================
Rank: 4
Candidate ID: 12011623
Category: ENGINEERING
FAISS Distance: 0.9940
----------------------------------------------------------------------------------------------------
ENGINEERING AND QUALITY TECHNICIAN Career Overview A highly experienced skilled graduate with Analytics degree with a very good experience in SAS, Web scraping, SQL, Predictive modelling and data visualization. Excellent ability in identifying data requirements for analysis, data cleaning, munging and model building; Ensures the organization uses it effectively to reach profit and growth objectives. Comfortable with data handling, modeling, and coding, and have an appreciation of what makes sense from a business standpoint. More than six years of experience working as a researcher, data analyst, and environmental science and Technology Instructor. Experience in SQL, data warehousing, maintaining, securing and stabilizing data layers and testing to identify data and product defects introduced in the system. Customer segmentation, product positioning and mapping and conjoint analysis Modelling: Design and implement statistical / predictive models and cutting edge algorithms utilizing diverse sources of data to predict Diversified experience with Engineering, Manufacturing, Retailing, Higher Education and IT /Data related companies Fascinated by learning cutting edge technologies, such as; Data Mining and Machine Learning Handled a team of 4 during my 3 years of Tech experience and managed more than 200 students and effectively evaluated the performance of each student and utilize assessment methods to judge overall progress during my teaching experience. Qualifications Ability

====================================================================================================
Rank: 5
Candidate ID: 12144825
Category: AVIATION
FAISS Distance: 0.9947
----------------------------------------------------------------------------------------------------
SOFTWARE ENGINEERING CO-OP Summary Highly skilled and Accomplished computer software specialist with more than 7+ years of technical experience in programming development across multiple platforms, software design, development and integration. Advanced knowledge of MySQL, CSS, C++ with expertise in all aspects of the software development life cycle, including requirements analysis, design, development and production support. Experienced Software Developer dedicated to constantly improving tools and infrastructure to maximize productivity, minimize system downtime and quickly respond to the changing needs of the business which does not exclude an intensive background in develop, testing, and debugging code, designing interfaces, and administrating systems and networks. Tenacious hard worker, self-directed and motivated, great leadership skills, able to work as a team, and adaptable to a quick changing technical environment. Highlights MySQL, PostgreSQL, SQLite, NoSQL, LevelDB Programming Languages: C, C++, Perl, PHP, Python, Go, JavaScript, Bash, SQL, Visual Basic, .NET Other Languages: CSS, HTML, XML, Markdown, Regular expression, SASS Operating Systems: Linux, Unix Tools: Netbeans, Vim, Visual Studio, MS Visio, MS Access, Wordpress, Git, Google Analytics, Docker, Microsoft Office package Strengths include: Full life software life cycle development expert Programming and designing Software testing / Troubleshooting / Advance critical thinking Database & Object oriented develo

In [36]:
import os
from dotenv import load_dotenv

load_dotenv("../.env")

api_key = os.getenv("GEMINI_API_KEY")

print("API key loaded:", api_key is not None)

API key loaded: True

In [50]:
import sys
from pathlib import Path

project_root = Path.cwd().parent

if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

In [51]:
from src.llm_evaluator import llm

In [52]:
print(llm.model)

gemini-2.5-flash

In [53]:
import src.llm_evaluator

print(src.llm_evaluator.__file__)

e:\NLP\rag-talent-search-engine\src\llm_evaluator.py

In [54]:
import importlib
import src.llm_evaluator

importlib.reload(src.llm_evaluator)

llm = src.llm_evaluator.llm

print(llm.model)

gemini-3.6-flash

In [55]:
response = llm.invoke(
    "Reply with only: API connection successful"
)

print(response.content)

e:\NLP\rag-talent-search-engine\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.6-flash' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[{'type': 'text', 'text': 'API connection successful', 'extras': {'signature': 'EpoECpcEARFNMg/GNRdqu4auBvfuh9Im+MTYWzPmGRBnQZg5naCEU4DU+bLZpcpPWyt7tTIy6xKmmtDAXHQOu2/zXh+1hUVOkZcCfWwJa+Se8btWa8yi68zmaxlRvkhI3xVPdoMtmEu7r2dc6+F0wmtwiSmm/Uw6gghucKu6xhKJvNGO/MofEM7t730W3i0wtE4jy7F8rtZZvlEwLqFJDHWwr/92riKE9S+plO71w54Q17PWcjzFDSzrV1nNku8aZxEiYhn3/bTOsHnLfYbuGHXbbPYPfXmE9RM8Gx8wQAa8QSBXSv7Vaq4ucr5x+pfRZ5zlxmuay9Xhchh2CjDhpNJup54Y8IVcq9V3fxW9RqHq/y4JjmIxx6ec4GULN/Qm+2zyYay7Vvsc3Wy/c8wR7Y5kHVcPs/POd/R2AzKPifzqjjH0ZGPu0fitlW9fygfI1N/7pXsx/DgCljEnAVj/2J82N62LTuGIG73OMBLk/4fYxCfvTwTcISMucXuu1efNtqfnvrGpuAXMyPq5p9hwhykaTWxTS59vd260gVtdKsY7MPBVI5WIgeOe4VvRz3YsB9z/Uy6rDJ2ulpG1SY5cDj89s8qCPgWH8UlYtu/sREZRgpoY0GphJZWfmC1rm1vnzo3jz24suXXD5pH1uSdeB5fl++vj3RvG28hdWTI/i4Erdc2mivRlJgxi794aio4TrtVAAjhcHHysPBkpCw=='}}]

In [56]:
response = llm.invoke(
    "Reply with only: API connection successful"
)

print(response.content[0]["text"])

e:\NLP\rag-talent-search-engine\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.6-flash' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

API connection successful